# generated by datamodel-codegen:
#   filename:  api_v5_9_2.yaml
#   timestamp: 2026-06-01T23:36:11+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel

from . import (
    GetDeviceConfigurationResponseData,
    GetDeviceInformationResponseData,
    GetDeviceStatusResponseData,
    GetServiceInformationResponseData,
    GetServiceStatusResponseData,
    IBISIPInt,
    OperationErrorMessage,
)


class SetDeviceConfigurationRequest(BaseModel):
    DeviceID: IBISIPInt | None = None


class GetDeviceConfigurationResponse(
    RootModel[GetDeviceConfigurationResponseData | OperationErrorMessage]
):
    root: GetDeviceConfigurationResponseData | OperationErrorMessage


class GetDeviceInformationResponse(
    RootModel[GetDeviceInformationResponseData | OperationErrorMessage]
):
    root: GetDeviceInformationResponseData | OperationErrorMessage


class GetDeviceStatusResponse(RootModel[GetDeviceStatusResponseData | OperationErrorMessage]):
    root: GetDeviceStatusResponseData | OperationErrorMessage


class GetServiceInformationResponse(
    RootModel[GetServiceInformationResponseData | OperationErrorMessage]
):
    root: GetServiceInformationResponseData | OperationErrorMessage


class GetServiceStatusResponse(RootModel[GetServiceStatusResponseData | OperationErrorMessage]):
    root: GetServiceStatusResponseData | OperationErrorMessage
