# generated by datamodel-codegen:
#   filename:  api_v5_9_2.yaml
#   timestamp: 2026-06-01T23:36:11+00:00

from __future__ import annotations

from pydantic import RootModel

from . import AllData, OperationErrorMessage


class GetAllDataResponse(RootModel[AllData | OperationErrorMessage]):
    root: AllData | OperationErrorMessage
