# generated by datamodel-codegen:
#   filename:  HUB-License_API_openapi_public_v1.json
#   timestamp: 2026-05-29T22:47:14+00:00

"""
Xovis SDK - Auto-Generated Hub License Models

Operates within the Control Plane.
Provides strictly validated Pydantic V2 models for querying and provisioning
edge-compute licenses (e.g., Object Detection) via the HUB Cloud.
"""

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel, StringConstraints


class Error(BaseModel):
    """Standardized HTTP error response envelope."""

    title: str | None = None
    detail: str | None = None


class PayPerUseStatus(Enum):
    """Billing lifecycle status for an active edge device."""

    ACTIVE = "ACTIVE"
    CANCELLED = "CANCELLED"
    INACTIVE = "INACTIVE"


class PayPerUseBillStatus(BaseModel):
    """Monthly billing resolution status."""

    month: str | None = None
    billed: bool | None = None


class BundleType(Enum):
    """Feature authorization bundles deployable to hardware."""

    OBJECT_DETECTION = "OBJECT_DETECTION"
    PEOPLE_ATTRIBUTES = "PEOPLE_ATTRIBUTES"


MACAddress = Annotated[str, StringConstraints(pattern=r"^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$")]


class SensorID(RootModel[MACAddress]):
    """Strictly validated MAC Address constraint for license targeting."""

    root: MACAddress = Field(..., examples=["12:34:56:78:9A:BC"])


class LicenseCreate(BaseModel):
    """Payload for provisioning a feature bundle onto a list of sensors."""

    bundle_types: list[BundleType] | None = None
    device_ids: list[SensorID] | None = None


class LicenseStatus(BaseModel):
    """Comprehensive authorization state and billing timeline for a hardware feature."""

    device_id: SensorID = Field(..., json_schema_extra={"ai_privacy": "BLOCK"})
    bundle_type: BundleType
    prepaid_used_days: int
    prepaid_total_days: int
    pay_per_use_bill_status: list[PayPerUseBillStatus] = Field(..., json_schema_extra={"ai_privacy": "BLOCK"})
    pay_per_use_status: PayPerUseStatus
    pay_per_use_active_until: date | None = None


class LicenseStatusResponse(BaseModel):
    """Array response containing license structures across a fleet."""

    license_status_list: list[LicenseStatus]
