# generated by datamodel-codegen:
#   filename:  api_v5_9_11.yaml
#   timestamp: 2026-06-01T23:39:18+00:00

from __future__ import annotations

from pydantic import RootModel

from . import GetDoorOpenStatesResponseData, OperationErrorMessage


class GetDoorOpenStatesResponse(RootModel[GetDoorOpenStatesResponseData | OperationErrorMessage]):
    root: GetDoorOpenStatesResponseData | OperationErrorMessage
